version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-network
  tracing-demo:
    image: jorgebo10/tracing-demo:latest
    ports:
      - "8080:8080"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-network
    depends_on:
      - jaeger
networks:
  jaeger-network:
    driver: bridge