apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
  name: eshop
  namespace: tracing-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-eshop
      protocol: TCP
  selector:
    app: eshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eshop
    version: v1
  name: eshop
  namespace: tracing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - name: eshop
          image: jorgebo10/tracing-demo:1.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: billing
  name: billing
  namespace: tracing-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-billing
      protocol: TCP
  selector:
    app: billing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: billing
    version: v1
  name: billing
  namespace: tracing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: jorgebo10/tracing-demo:1.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: delivery
  name: delivery
  namespace: tracing-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-delivery
      protocol: TCP
  selector:
    app: delivery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: delivery
  name: delivery
  namespace: tracing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: jorgebo10/tracing-demo:1.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory
  name: inventory
  namespace: tracing-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-inventory
      protocol: TCP
  selector:
    app: inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory
    version: v1
  name: inventory
  namespace: tracing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: jorgebo10/tracing-demo:1.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logistics
  name: logistics
  namespace: tracing-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http-logistics
      protocol: TCP
  selector:
    app: logistics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logistics
    version: v1
  name: logistics
  namespace: tracing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics
  template:
    metadata:
      labels:
        app: logistics
    spec:
      containers:
        - name: logistics
          image: jorgebo10/tracing-demo:1.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: eshop-gateway
  namespace: tracing-demo
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop
  namespace: tracing-demo
spec:
  hosts:
    - "*"
  gateways:
    - eshop-gateway
  http:
    - match:
        - uri:
            prefix: /checkout
      route:
        - destination:
            host: eshop.tracing-demo.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: tracing.istio-system.svc.cluster.local
            port:
              number: 80
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eshop-operator
  namespace: tracing-demo
spec:
  profile: demo
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
